permalink:           pretty
# Setup
title:               'Компьютерные технологии в механике'
homepage_title:      как пользоваться страничкой
url:                 https://pppmmm131313.github.io/
baseurl:             ''

src:                 "."
default_theme:       "rust"

# For Maths
markdown:            kramdown
 
prologues:
  - path: 1_semester.md
  - path: about.md
  - path: tools.md
